apiVersion: v1
kind: ConfigMap
metadata:
  name: lorenzo-campos-front-configmap
  namespace: default
data:
  PORT: "60"
  BACKEND_URL: "http://lorenzo-campos-back-service:7070"
  VITE_API_URL: "http://lorenzo-campos-back-service:7070"
