apiVersion: apps/v1
kind: Deployment
metadata:
  name: lorenzo-campos-back-deployment
  namespace: default
  labels:
    app: lorenzo-campos-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lorenzo-campos-back
  template:
    metadata:
      labels:
        app: lorenzo-campos-back
    spec:
      containers:
      - name: lorenzo-campos-back
        image: lorenzo01/as232s5-backend:latest
        ports:
        - containerPort: 7070
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: lorenzo-campos-back-configmap
        - secretRef:
            name: lorenzo-campos-back-secret
            optional: true
        livenessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
